version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_NAME}
    expose:
      - 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis/redis-stack:latest
    restart: always
    container_name: redis
    command: redis-server --requirepass ${PASSWORD} --loadmodule /opt/redis-stack/lib/redisearch.so --loadmodule /opt/redis-stack/lib/rejson.so --loadmodule /opt/redis-stack/lib/redisbloom.so --loadmodule /opt/redis-stack/lib/redistimeseries.so
    expose:
      - 6379
    volumes:
      - redis-data:/data
    env_file:
      - .env

  bot:
    build:
      context: .
      dockerfile: bot.dockerfile
    restart: always
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    volumes:
      - ./:/bot

  api:
    build:
      context: .
      dockerfile: api.dockerfile
    restart: always
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    ports:
      - "9000:9000"
    volumes:
      - ./:/api

volumes:
  postgres-data:
  redis-data:
